baseURL: "https://jacklc3.github.io/"
title: Jack Liell-Cock
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        - name: Talks
          url: talks/
          weight: 3
        - name: Notes
          url: notes/
          weight: 4

params:
    description: "This website hosts Jack Liell-Cock's research papers, and contact information."
    author: "Jack Liell-Cock"
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["papers","talks","notes"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
        enabled: true
        title: Jack Liell-Cock
        subtitle: "Hi! I am a PhD student in Computer Science at the University of Oxford studying programming langauge theory under Sam Staton.
        I am primarity interested in semantics of computational effects and I work with tools such as universal algebra and monads.
        I have crossed into areas such as concurrency and probabilistic programming -- see my papers tab for more info.
        Outside of academia I am a keen traveller, climber, runner, and skier."
        imageUrl: "picture.jpeg"
        imageWidth: 160
        imageHeight: 160
        buttons:
          - name: Papers
            url: papers/
          - name: Talks
            url: talks/
          - name: Notes
            url: notes/

    socialIcons:
        - name: Email
          url: mailto:jack.liell-cock@cs.ox.ac.uk
        - name: ORCID
          url: https://orcid.org/0009-0005-7121-8095
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=PSKAqM4AAAAJ
        - name: GitHub
          url: https://github.com/jacklc3
        - name: Location
          url: location/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jack Liell-Cock"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
